name: New Feature
description: New Feature to the system
title: "[Feature-Task]"
labels: 'enhancement'
assignees: 'mohamedmtc'
body:
- type: markdown
  value: "## Welcome!"
- type: input
  id: os
  attributes:
    label: Bisuness File 
    description: "The name of the bsuiness file in the application layer"
    placeholder: "Get .... _CMPLX"
   validations:
     required: true 
 
