name: New Feature
description: New Feature to the system
title: "[Feature-Task]"
labels: 'enhancement'
assignees: 'mohamedmtc'
body:
  - type: markdown
    attributes:
      value: |
        Before creating new task, please review  the behaviour in the existing system. 
        
        ---
        
        now we will set the Defination of ready points for the new task.
